// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwpBRZ7iKQ6tuJavnZoJaDfvRjwrgpsbg',
    appId: '1:500704221149:web:91b76aa67bae62d2a70834',
    messagingSenderId: '500704221149',
    projectId: 'dustbank-9d6af',
    authDomain: 'dustbank-9d6af.firebaseapp.com',
    storageBucket: 'dustbank-9d6af.firebasestorage.app',
    measurementId: 'G-J5RDGFEBY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMuAve4f4JUcZgQ2gEB8jyLlBlMkXHLrw',
    appId: '1:500704221149:android:dec2927434ccffeda70834',
    messagingSenderId: '500704221149',
    projectId: 'dustbank-9d6af',
    storageBucket: 'dustbank-9d6af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZOB3UwBFkJlgIAIRAlN0NvV1z_qhfSJQ',
    appId: '1:500704221149:ios:044ff531d2d49131a70834',
    messagingSenderId: '500704221149',
    projectId: 'dustbank-9d6af',
    storageBucket: 'dustbank-9d6af.firebasestorage.app',
    iosBundleId: 'com.example.screenTimeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZOB3UwBFkJlgIAIRAlN0NvV1z_qhfSJQ',
    appId: '1:500704221149:ios:044ff531d2d49131a70834',
    messagingSenderId: '500704221149',
    projectId: 'dustbank-9d6af',
    storageBucket: 'dustbank-9d6af.firebasestorage.app',
    iosBundleId: 'com.example.screenTimeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwpBRZ7iKQ6tuJavnZoJaDfvRjwrgpsbg',
    appId: '1:500704221149:web:71428cbebda8bb7ea70834',
    messagingSenderId: '500704221149',
    projectId: 'dustbank-9d6af',
    authDomain: 'dustbank-9d6af.firebaseapp.com',
    storageBucket: 'dustbank-9d6af.firebasestorage.app',
    measurementId: 'G-EQSM11LMX3',
  );

}